// <auto-generated />
namespace NewsApplication.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class n : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(n));
        
        string IMigrationMetadata.Id
        {
            get { return "201504220624303_n"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
